### ISSUE TITLE
Can't build with zig 0.10.0.3685

### ISSUE THREAD

**Issue by realgdman** [thimenesup/GodotZigBindings#3]
There are couple of errors
First is easy, at https://github.com/thimenesup/GodotZigBindings/blob/master/binding_generator.zig#L282
changed to something like
`const class_is_instanciable = if (class.get("instanciable").?.Bool) "true" else "false";`
`const class_is_singleton = if (class.get("singleton").?.Bool) "true" else "false";`

Second, in https://github.com/thimenesup/GodotZigBindings/blob/master/src/core/basis.zig#L270
There are two places where compiler complains about space between `c -s`

The third one is hard to me to understand

src\core\gdnative_api_types.zig:173:5: error: extern structs cannot contain fields of type '?fn(?*const anyopaque, [*c]const u8, core.gdnative_api_types.godot_gdnative_api_version, core.gdnative_api_types.godot_gdnative_api_version) callconv(.C) void'
    report_version_mismatch: ?fn (?*const godot_object, [*c]const u8, godot_gdnative_api_version, godot_gdnative_api_version) callconv(.C) void,
src\core\gdnative_api_types.zig:173:5: note: only pointer like optionals are extern compatible

src\core\gdnative_api_types.zig:277:5: error: extern structs cannot contain fields of type '?fn(?*anyopaque, ?*anyopaque) callconv(.C) ?*anyopaque'
    create_func: ?fn (?*godot_object, ?*anyopaque) callconv(.C) ?*anyopaque,
src\core\gdnative_api_types.zig:277:5: note: only pointer like optionals are extern compatible

src\core\gdnative_api.zig:861:5: error: extern structs cannot contain fields of type '?fn(?*anyopaque, [*c]const u8, [*c]const u8, c_int, [*c]const core.gdnative_api_types.godot_method_arg) callconv(.C) void'
    godot_nativescript_set_method_argument_information: ?fn (?*anyopaque, [*c]const u8, [*c]const u8, c_int, [*c]const gd.godot_method_arg) callconv(.C) void,
src\core\gdnative_api.zig:861:5: note: only pointer like optionals are extern compatible

Note that I can build it with older zig (0.10.0.3394 for example), but can't make it work on Win64. DLL loads in Godot, prints debug messages from godot_nativescript_init(), but no actual TestNode2D methods are registered, all calls fails and even nativeScript.get_script_method_list() not listing them.

**Comment by thimenesup** [comment]
I would wait until it 0.10 gets a stable release before actually trying to fix anything, these bindings are made for the last stable release 0.9.1.

**Comment by realgdman** [comment]
I see, it wasn't mentioned in readme so I assumed it was close to master branch. With 0.9.1 it indeed working on windows. However it seems Zig (due to LLVM bug) unable to build .so for android yet, so I'm exploring totally another way now, with `zig build -ofmt=c` emitting C-code which later will be fed into usual GDNative or Godot module pipeline. Thanks for your project for some insights, though.
