### ISSUE TITLE
`Node.getNode`: expected type `?*anyopaque`, found `*?*anyopaque`

### ISSUE THREAD

**Issue by Des-Nerger** [thimenesup/GodotZigBindings#9]
`Node.getNode` doesn't seem to work in 4.0 yet? I tried to add a test case:
```diff
--- a/test_example/src/test_node2d.zig
+++ b/test_example/src/test_node2d.zig
@@ -45,0 +46 @@ pub const TestNode2D = struct {
+        ClassDB.bindMethod(Self, testGetNode, "test_get_node", .{});
@@ -110,0 +112,11 @@ pub const TestNode2D = struct {
+    pub fn testGetNode(self: *const Self) void {
+        const NodePath = gdextension.core_types.NodePath;
+        {
+            var node_path_string = String.initUtf8(@typeName(Self));
+            defer node_path_string.deinit();
+            var node_path = NodePath.initString(&node_path_string);
+            defer node_path.deinit();
+            _ = self.base.base.base.getNode(&node_path);
+        }
+    }
+
```
But it failed to build, with:
```
src/godot.zig:195:70: error: expected type '?*anyopaque', found '*?*anyopaque'
    interface.?.object_method_bind_ptrcall.?(mb, instance, &payload, &ret);
                                                                     ^~~~
src/godot.zig:195:70: note: cannot implicitly cast double pointer '*?*anyopaque' to anyopaque pointer '?*anyopaque'
referenced by:
    getNode: src/gen/classes/node.zig:249:37
    testGetNode: src/test_node2d.zig:119:36
```

**Comment by thimenesup** [comment]
Fixed by a9f6d3d.
